steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-17b596cb5e63/my-app-repo/flask-app:$SHORT_SHA', '.']

# Step 2: Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-17b596cb5e63/my-app-repo/flask-app:$SHORT_SHA']

# Step 3: Set image in Kubernetes manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s|IMAGE_NAME|us-central1-docker.pkg.dev/qwiklabs-gcp-01-17b596cb5e63/my-app-repo/flask-app:$SHORT_SHA|g" kubernetes/deployment.yaml

# Step 4: Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    [
      'apply',
      '-f',
      'kubernetes/deployment.yaml',
      '-f',
      'kubernetes/service.yaml'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

images:
- 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-17b596cb5e63/my-app-repo/flask-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY


